apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: example-external-keycloak
  labels:
    app: external-sso
spec:
  unmanaged: true
  external:
    enabled: true
    url: https://sub.keycloak
    adminUsername: admin
    adminPassword: admin
