apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: example-external-keycloak
  labels:
    app: default-sso
spec:
  unmanaged: true
  external:
    enabled: true
    url: http://keycloak-http.default
    adminUsername: admin
    adminPassword: admin
