apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: keycloak-operator
  template:
    metadata:
      labels:
        name: keycloak-operator
    spec:
      serviceAccountName: keycloak-operator
      containers:
        - name: keycloak-operator
          # When developing operator changes, build a new docker image and update this reference i.e. keycloak-operator:latest
          image: harbor.ssk8s.vibrenthealth.com/vibrent-ops/keycloak-operator:master
          command:
          - keycloak-operator
          imagePullPolicy: Never
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "keycloak-operator"
            - name: CLIENT_MAX_CONCURRENT_RECONCILES
              value: "1"
            - name: REALM_MAX_CONCURRENT_RECONCILES
              value: "1"
            - name: SYNC_PERIOD
              value: "30m"
      imagePullSecrets:
        - name: harbor-ssk8s-vibrenthealth-com-vibrent-ops-read-only
