---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: default-participant
  labels:
    app: default-participant
spec:
  realm:
    id: default-participant
    realm: default-participant
    displayName: "Vibrent Operator Testing Realm"
    accessTokenLifespan: 288
    accessTokenLifespanForImplicitFlow: 417
    enabled: true
    sslRequired: none
    registrationAllowed: true
    registrationEmailAsUsername: false
    rememberMe: false
    verifyEmail: true
    loginWithEmailAllowed: false
    duplicateEmailsAllowed: true
    resetPasswordAllowed: true
    editUsernameAllowed: true
    bruteForceProtected: true
    permanentLockout: false
    maxFailureWaitSeconds: 3600
    minimumQuickLoginWaitSeconds: 60
    waitIncrementSeconds: 3600
    quickLoginCheckMilliSeconds: 1000
    maxDeltaTimeSeconds: 43200
    failureFactor: 5
    smtpServer:
      password: "**********"
      starttls: 'true'
      auth: 'true'
      port: '587'
      host: smtp.mailtrap.io
      from: info_kube@vibrenthealthtest.com
      fromDisplayName: ''
      ssl: 'false'
      user: 0db3a12afc6ceb
    loginTheme: participant
    accountTheme: participant
    emailTheme: participant
    eventsEnabled: false
    eventsListeners:
      - api-post
      - login-externalID
      - login-locale
      - jboss-logging
      - metrics-listener
    adminEventsEnabled: false
    adminEventsDetailsEnabled: false
    identityProviders: [ ]
    internationalizationEnabled: false
    authenticationFlows:
      - alias: Choose Token/Email
        providerId: basic-flow
        topLevel: false
        builtIn: false
        authenticationExecutions:
          - authenticator: vrp-token-reset-credential
            authenticatorFlow: false
            requirement: ALTERNATIVE
            priority: 0
            userSetupAllowed: false
          - authenticatorFlow: true
            requirement: ALTERNATIVE
            priority: 1
            flowAlias: Choose User SubFlow
            userSetupAllowed: false
      - alias: Choose User SubFlow
        providerId: basic-flow
        topLevel: false
        builtIn: false
        authenticationExecutions:
          - authenticator: vrp-choose-user
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 0
            userSetupAllowed: false
          - authenticator: vrp-reset-credential-email
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 1
            userSetupAllowed: false
      - alias: Handle Existing Account
        description: Handle what to do if there is existing account with same email/username
          like authenticated identity provider
        providerId: basic-flow
        topLevel: false
        builtIn: true
        authenticationExecutions:
          - authenticator: idp-confirm-link
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 10
            userSetupAllowed: false
          - authenticator: idp-email-verification
            authenticatorFlow: false
            requirement: ALTERNATIVE
            priority: 20
            userSetupAllowed: false
          - authenticatorFlow: true
            requirement: ALTERNATIVE
            priority: 30
            flowAlias: Verify Existing Account by Re-authentication
            userSetupAllowed: false
      - alias: Registration
        description: registration flow
        providerId: basic-flow
        topLevel: false
        builtIn: false
        authenticationExecutions:
          - authenticator: registration-page-form
            authenticatorFlow: true
            requirement: REQUIRED
            priority: 0
            flowAlias: participant registration form
            userSetupAllowed: false
      - alias: Verify Existing Account by Re-authentication
        description: Reauthentication of existing account
        providerId: basic-flow
        topLevel: false
        builtIn: true
        authenticationExecutions:
          - authenticator: idp-username-password-form
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 10
            userSetupAllowed: false
          - authenticatorFlow: true
            requirement: CONDITIONAL
            priority: 20
            flowAlias: Verify Existing Account by Re-authentication - auth-otp-form - Conditional
            userSetupAllowed: false
      - alias: Verify Existing Account by Re-authentication - auth-otp-form - Conditional
        description: Flow to determine if the auth-otp-form authenticator should be used
          or not.
        providerId: basic-flow
        topLevel: false
        builtIn: true
        authenticationExecutions:
          - authenticator: conditional-user-configured
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 10
            userSetupAllowed: false
          - authenticator: auth-otp-form
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 20
            userSetupAllowed: false
      - alias: browser
        description: browser based authentication
        providerId: basic-flow
        topLevel: true
        builtIn: true
        authenticationExecutions:
          - authenticator: auth-cookie
            authenticatorFlow: false
            requirement: ALTERNATIVE
            priority: 10
            userSetupAllowed: false
          - authenticator: auth-spnego
            authenticatorFlow: false
            requirement: DISABLED
            priority: 20
            userSetupAllowed: false
          - authenticator: identity-provider-redirector
            authenticatorFlow: false
            requirement: ALTERNATIVE
            priority: 25
            userSetupAllowed: false
          - authenticatorFlow: true
            requirement: ALTERNATIVE
            priority: 30
            flowAlias: forms
            userSetupAllowed: false
      - alias: clients
        description: Base authentication for clients
        providerId: client-flow
        topLevel: true
        builtIn: true
        authenticationExecutions:
          - authenticator: client-secret
            authenticatorFlow: false
            requirement: ALTERNATIVE
            priority: 10
            userSetupAllowed: false
          - authenticator: client-jwt
            authenticatorFlow: false
            requirement: ALTERNATIVE
            priority: 20
            userSetupAllowed: false
          - authenticator: client-secret-jwt
            authenticatorFlow: false
            requirement: ALTERNATIVE
            priority: 30
            userSetupAllowed: false
          - authenticator: client-x509
            authenticatorFlow: false
            requirement: ALTERNATIVE
            priority: 40
            userSetupAllowed: false
      - alias: direct grant
        description: OpenID Connect Resource Owner Grant
        providerId: basic-flow
        topLevel: true
        builtIn: true
        authenticationExecutions:
          - authenticator: direct-grant-validate-username
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 10
            userSetupAllowed: false
          - authenticator: direct-grant-validate-password
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 20
            userSetupAllowed: false
          - authenticator: direct-grant-validate-otp
            authenticatorFlow: false
            requirement: DISABLED
            priority: 30
            userSetupAllowed: false
      - alias: docker auth
        description: Used by Docker clients to authenticate against the IDP
        providerId: basic-flow
        topLevel: true
        builtIn: true
        authenticationExecutions:
          - authenticator: docker-http-basic-authenticator
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 10
            userSetupAllowed: false
      - alias: first broker login
        description: Actions taken after first broker login with identity provider account,
          which is not yet linked to any Keycloak account
        providerId: basic-flow
        topLevel: true
        builtIn: true
        authenticationExecutions:
          - authenticatorConfig: review profile config
            authenticator: idp-review-profile
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 10
            userSetupAllowed: false
          - authenticatorConfig: create unique user config
            authenticator: idp-create-user-if-unique
            authenticatorFlow: false
            requirement: ALTERNATIVE
            priority: 20
            userSetupAllowed: false
          - authenticatorFlow: true
            requirement: ALTERNATIVE
            priority: 30
            flowAlias: Handle Existing Account
            userSetupAllowed: false
      - alias: forms
        description: Username, password, otp and other auth forms.
        providerId: basic-flow
        topLevel: false
        builtIn: true
        authenticationExecutions:
          - authenticator: auth-username-password-form
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 10
            userSetupAllowed: false
          - authenticatorFlow: true
            requirement: CONDITIONAL
            priority: 20
            flowAlias: forms - auth-otp-form - Conditional
            userSetupAllowed: false
      - alias: forms - auth-otp-form - Conditional
        description: Flow to determine if the auth-otp-form authenticator should be used
          or not.
        providerId: basic-flow
        topLevel: false
        builtIn: true
        authenticationExecutions:
          - authenticator: conditional-user-configured
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 10
            userSetupAllowed: false
          - authenticator: auth-otp-form
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 20
            userSetupAllowed: false
      - alias: http challenge
        description: An authentication flow based on challenge-response HTTP Authentication
          Schemes
        providerId: basic-flow
        topLevel: true
        builtIn: true
        authenticationExecutions:
          - authenticator: no-cookie-redirect
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 10
            userSetupAllowed: false
          - authenticator: basic-auth
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 20
            userSetupAllowed: false
          - authenticator: basic-auth-otp
            authenticatorFlow: false
            requirement: DISABLED
            priority: 30
            userSetupAllowed: false
          - authenticator: auth-spnego
            authenticatorFlow: false
            requirement: DISABLED
            priority: 40
            userSetupAllowed: false
      - alias: participant browser
        description: browser based authentication
        providerId: basic-flow
        topLevel: true
        builtIn: false
        authenticationExecutions:
          - authenticator: auth-cookie
            authenticatorFlow: false
            requirement: ALTERNATIVE
            priority: 10
            userSetupAllowed: false
          - authenticator: auth-spnego
            authenticatorFlow: false
            requirement: DISABLED
            priority: 20
            userSetupAllowed: false
          - authenticator: identity-provider-redirector
            authenticatorFlow: false
            requirement: ALTERNATIVE
            priority: 25
            userSetupAllowed: false
          - authenticatorFlow: true
            requirement: ALTERNATIVE
            priority: 30
            flowAlias: participant browser forms
            userSetupAllowed: false
      - alias: participant browser forms
        description: Username, password, otp and other auth forms.
        providerId: basic-flow
        topLevel: false
        builtIn: false
        authenticationExecutions:
          - authenticator: auth-vrp-login-form
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 0
            userSetupAllowed: false
      - alias: participant registration
        description: registration flow
        providerId: basic-flow
        topLevel: true
        builtIn: false
        authenticationExecutions:
          - authenticator: auth-cookie
            authenticatorFlow: false
            requirement: DISABLED
            priority: 0
            userSetupAllowed: false
          - authenticator: registration-page-form
            authenticatorFlow: true
            requirement: ALTERNATIVE
            priority: 1
            flowAlias: Registration
            userSetupAllowed: false
      - alias: participant registration form
        description: registration form
        providerId: form-flow
        topLevel: false
        builtIn: false
        authenticationExecutions:
          - authenticator: vibrent-create-account
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 0
            userSetupAllowed: false
          - authenticator: reg-form-password-no-confirm
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 1
            userSetupAllowed: false
      - alias: participant reset credentials
        providerId: basic-flow
        topLevel: true
        builtIn: false
        authenticationExecutions:
          - authenticatorFlow: true
            requirement: REQUIRED
            priority: 0
            flowAlias: Choose Token/Email
            userSetupAllowed: false
          - authenticator: answer-secret-questions
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 1
            userSetupAllowed: false
          - authenticator: reset-password
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 2
            userSetupAllowed: false
      - alias: registration
        description: registration flow
        providerId: basic-flow
        topLevel: true
        builtIn: true
        authenticationExecutions:
          - authenticator: registration-page-form
            authenticatorFlow: true
            requirement: REQUIRED
            priority: 10
            flowAlias: registration form
            userSetupAllowed: false
      - alias: registration form
        description: registration form
        providerId: form-flow
        topLevel: false
        builtIn: true
        authenticationExecutions:
          - authenticator: registration-user-creation
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 20
            userSetupAllowed: false
          - authenticator: registration-profile-action
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 40
            userSetupAllowed: false
          - authenticator: registration-password-action
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 50
            userSetupAllowed: false
          - authenticator: registration-recaptcha-action
            authenticatorFlow: false
            requirement: DISABLED
            priority: 60
            userSetupAllowed: false
      - alias: reset credentials
        description: Reset credentials for a user if they forgot their password or something
        providerId: basic-flow
        topLevel: true
        builtIn: true
        authenticationExecutions:
          - authenticator: reset-credentials-choose-user
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 10
            userSetupAllowed: false
          - authenticator: reset-credential-email
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 20
            userSetupAllowed: false
          - authenticator: reset-password
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 30
            userSetupAllowed: false
          - authenticator: reset-otp
            authenticatorFlow: false
            requirement: DISABLED
            priority: 40
            userSetupAllowed: false
      - alias: saml ecp
        description: SAML ECP Profile Authentication Flow
        providerId: basic-flow
        topLevel: true
        builtIn: true
        authenticationExecutions:
          - authenticator: http-basic-authenticator
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 10
            userSetupAllowed: false
    authenticatorConfig:
      - alias: create unique user config
        config:
          require.password.update.after.registration: 'false'
      - alias: review profile config
        config:
          update.profile.on.first.login: missing
    userManagedAccessAllowed: false
  instanceSelector:
    matchLabels:
      app: default-sso