name: CI
on: 
  push:
    branches: 
      - master
      - release/*
  pull_request:
    branches: 
      - master
      - release/*
jobs:
  build:
    name: Tests
    runs-on: ubuntu-22.04
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Unit tests
      run: |
        make test/unit
    - name: Start minikube
      uses: manusa/actions-setup-minikube@v2.10.0
      with:
        minikube version: 'v1.29.0'
        kubernetes version: 'v1.25.9'
        driver: 'docker'
    - name: Configure Minikube
      run: |
        minikube addons enable ingress
        hack/modify_etc_hosts.sh "keycloak.local"
    - name: Run e2e tests
      run: |
        make cluster/prepare
        make test/e2e
        make cluster/clean
    - name: Run e2e tests for local image
      run: |
        make test/e2e-local-image
